version: '3'
services:
  db:
    image: "postgres:alpine"
    ports:
       - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - db
    environment: 
       GUBY_PASSWORD : 'abcd1234'
    volumes:
      - ./:/code
