version: '3'
services:
  db:
    image: "postgres:alpine"
    ports:
       - "5432:5432"
    environment:
      - POSTGRES_USER=guby_admin
      - POSTGRES_PASSWORD=abcd1234
      - POSTGRES_DB=guby
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - db
    environment: 
       GUBY_PASSWORD : 'abcd1234'