version: '3'
services:
  db:
    image: "postgres:alpine"
    ports:
       - "5432:5432"
    env_file: .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - db
    env_file: .env
    environment: 
       GUBY_PASSWORD : 'abcd1234'
    volumes:
      - ./:/code
#   rocketchat:
#     image: rocketchat/rocket.chat:latest
#     command: >
#       bash -c
#         "for i in `seq 1 30`; do
#           node main.js &&
#           s=$$? && break || s=$$?;
#           echo \"Tried $$i times. Waiting 5 secs...\";
#           sleep 5;
#         done; (exit $$s)"
#     restart: unless-stopped
#     volumes:
#       - ./uploads:/app/uploads
#     environment:
#       - PORT=3000
#       - ROOT_URL=http://localhost:3000
#       - MONGO_URL=mongodb://mongo:27017/rocketchat
#       - MONGO_OPLOG_URL=mongodb://mongo:27017/local
#       - MAIL_URL=smtp://smtp.email
#       - OVERWRITE_SETTING_Show_Setup_Wizard=completed
#       - ADMIN_USERNAME=guby
#       - ADMIN_PASSWORD=guby123
#       - ADMIN_EMAIL=guby@guby.live
# #       - HTTP_PROXY=http://proxy.domain.com
# #       - HTTPS_PROXY=http://proxy.domain.com
#     depends_on:
#       - mongo
#     ports:
#       - 3000:3000
#     labels:
#       - "traefik.backend=rocketchat"
#       - "traefik.frontend.rule=Host: your.domain.tld"
#   mongo:
#     image: mongo:4.0
#     restart: unless-stopped
#     volumes:
#      - ./data/db:/data/db
#      #- ./data/dump:/dump
#     command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
#     labels:
#       - "traefik.enable=false"
#     ports:
#       - 27017:27017

#   # this container's job is just run the command to initialize the replica set.
#   # it will run the command and remove himself (it will not stay running)
#   mongo-init-replica:
#     image: mongo:4.0
#     command: >
#       bash -c
#         "for i in `seq 1 30`; do
#           mongo mongo/rocketchat --eval \"
#             rs.initiate({
#               _id: 'rs0',
#               members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
#           s=$$? && break || s=$$?;
#           echo \"Tried $$i times. Waiting 5 secs...\";
#           sleep 5;
#         done; (exit $$s)"
#     depends_on:
#       - mongo
